### ISSUE TITLE
Visual send with 'ctr' starts from where cursor initiated visual selection

### ISSUE THREAD

**Issue by danjenson** [Vigemus/iron.nvim#104]
If you send a block in visual mode but the cursor started the highlight from anywhere but the first character of the first line, it only sends from the initial location of the cursor to the end of the visual block. This means that if you highlight a block from the bottom up, it sends nothing. Using Fedora 29, python 3.7, nvim v0.3.3, commit 72cc5c84670ec4d57e9dd91081eea838c82a6be7.

**Comment by ohspc89** [comment]
Seeing the same issue: Ubuntu 18.04, python 3.6, nvim v0.3.1

**Comment by a-vrma** [comment]
Same issue here: macOS 10.13, python 3.7.2, nvim 0.3.4

**Comment by danjenson** [comment]
same

**Comment by a-vrma** [comment]
I've moved on to using vim-slime in the meantime. Does basically the same thing.

**Comment by randomizedthinking** [comment]
I use vim-slime too: it is nice. Yet I feel the approach used by iron.nvim is the way to go, even it is not quite mature as of now.

**Comment by randomizedthinking** [comment]
The issue is now resolved. @danjenson please confirm...

**Comment by danjenson** [comment]
Well, it's partially fixed. You can highlight from the bottom up, but for the topmost line highlighted, it only sends from the current cursor to the end of the line. So in the following example:

line 1
line 2
line 3

If you visual highlight from line 3 and go up, but your cursor is on the 'e' in 'line 1' when you send, it will send

e 1
line 2
line 3

To the console.

So, almost fixed!

**Comment by randomizedthinking** [comment]
Thanks... Will check it out out.

**Comment by randomizedthinking** [comment]
@danjenson can you check again whether the problem is resolved?

**Comment by danjenson** [comment]
fixed! closing
